# IT Admin Agent Configuration

# System settings
system:
  name: "IT Admin Agent"
  version: "0.1.0"
  log_level: "INFO"
  environment: "development"  # Options: development, testing, production

# Agent settings
agents:
  task_manager:
    enabled: true
    max_concurrent_tasks: 5
    default_priority: "medium"
  
  diagnostics:
    enabled: true
    timeout_seconds: 300
    max_retries: 3
  
  execution:
    enabled: true
    timeout_seconds: 600
    max_concurrent_executions: 3
    sandbox_enabled: true
  
  learning:
    enabled: true
    learning_threshold: 0.8
    similarity_threshold: 0.75
  
  validation:
    enabled: true
    strict_mode: false

# Knowledge base settings
knowledge_base:
  vector_db:
    type: "chroma"
    path: "./data/vector_store"
    embedding_model: "text-embedding-ada-002"
    dimension: 1536
  
  relational_db:
    type: "sqlite"
    path: "./data/sqlite/itadmin.db"
    backup_enabled: true
    backup_frequency: "daily"

# Task planning settings
task_planner:
  llm:
    model: "gpt-4"
    temperature: 0.2
    max_tokens: 2000
  
  default_checks:
    - syntax_validation
    - security_scan
    - impact_assessment

# Execution engine settings
execution:
  sandbox:
    enabled: true
    isolation_level: "container"  # Options: process, container, vm
  
  remote_execution:
    connection_timeout: 30
    retry_attempts: 3
    default_protocol: "ssh"
  
  local_execution:
    timeout: 300
    allowed_directories:
      - "./scripts"
      - "./tools"

# Security settings
security:
  encryption:
    algorithm: "AES-256"
  
  authentication:
    jwt_expiration_minutes: 60
    password_hash_algorithm: "bcrypt"
  
  authorization:
    rbac_enabled: true
    default_role: "readonly"
  
  credential_store:
    type: "encrypted_file"  # Options: encrypted_file, vault
    path: "./data/credentials"

# Human interaction settings
human_interaction:
  default_mode: "supervised"  # Options: guided, supervised, semi-autonomous, autonomous
  
  approvals:
    required_for:
      - network_changes
      - production_server_modifications
      - security_policy_changes
      - database_schema_changes
  
  notifications:
    channels:
      - type: "email"
        enabled: true
      - type: "slack"
        enabled: false
      - type: "web"
        enabled: true
  
  dashboard:
    refresh_interval: 5  # seconds
    history_retention_days: 30

# Monitoring settings
monitoring:
  metrics:
    enabled: true
    prometheus_port: 9091
  
  logging:
    file_path: "./logs"
    rotation: "daily"
    retention_days: 30
  
  alerts:
    threshold_cpu_percent: 90
    threshold_memory_percent: 90
    threshold_disk_percent: 85

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8501"
  rate_limit:
    enabled: true
    requests_per_minute: 60 